services:
  - type: web
    name: anime-voting
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: SOLID_QUEUE_IN_PUMA
        value: "true"
      - key: RAILS_STORAGE_SERVICE
        value: supabase
      - key: SUPABASE_ACCESS_KEY_ID
        sync: false
      - key: SUPABASE_SECRET_ACCESS_KEY
        sync: false
      - key: SUPABASE_BUCKET
        sync: false
      - key: SUPABASE_ENDPOINT
        sync: false
      - key: SUPABASE_REGION
        value: us-east-1
